print(f'AI: Hello I Am Here To Help You With Your Worries And Concerns')
print(f'Ai:You Can Share Anything With Me And I Will Listen and i only have 25 Responses')
print((f'AI:Well Lets Start With Your Name'))
input_response = input('You: ')
print(f'AI:Hi There {input_response} That Is A Nice Name ')
print(f'AI:Now You Can Tell Me About Your Worries or Concerns')
input('You: ')
print(f'AI: Remember That people Are Gonna Always Be There For You And Care For Who You Are')
input('You: ')
print(f'AI: You Are Not Alone In This World And I Am Here To Help You')
input('You: ')
print(f'AI: well once it is done you will feel better')
input('You: ')
print(f'AI: If You Need Anything Else I Am Here For You')
input('You: ')
print(f'AI: You Are Stronger Than You Think And Capable Of Overcoming Any Challenge')
input('You: ')
print(f'AI: Awesome Please Remember That You Are Valued And Loved')
input('You: ')
print(f'AI: Ok Well I Will Always Be Here For You And Every One Else Will Be Too')
input('You: ')
print(f'AI: You Are Important And Your Feelings Matter')
input('You: ')
print(f'AI: That Is Normal Everyone Feels That Way Sometimes')
print(f'AI: If Not Then Then Would Not Be Human Or Normal So Just Rememeber That is it ok To Feel That Way')
input('You: ')
print(f'AI: Is There Anything Else You Would Like To Share Or Talk About or Should We End It Here or stick with this and up to 20 Responses')
input('You: ')
print(f'AI: Great I Am Glad I Could Be Here For You')
input('You: ')
print(f'AI: You Are Not Alone In This World And There Are People Who Care About You')
input('You: ')
print(f'AI: If You Ever Need Someone To Talk To I Am Here For You')
input('You: ')
print(f'AI:You Are Stronger Than You Think And Capable Of Overcoming Any Challenge')
input('You: ')
print(f'AI: Remember That You Are Valued And Loved Just The Way You Are')
input('You: ')
print(f'AI: If You Need Anything Else I Am Here For You')
input('You: ')
print(f'AI: Thank You For Sharing With Me And I Am Glad I Could Be Here For You')
input('You: ')
print(f'AI: Goodbye And Take Care')
input('You: ')
print(f'AI: Remember That You Are Not Alone And There Are People Who Care About You')
input('You: ')
print(f'AI:If You Ever Need Someone To Talk To I Am Here For You')
input('You: ')
print(f'AI: Bye And Take Care')
input('You: ')
print(f'AI: Remember That You Are Valued And Loved Just The Way You Are')
input('You: ')
print(f'AI: Goodbye And Take Care')
input('You: '
      )
print((f'Please Rate Your Experience From 1 To 10 With 10 Being The Best'))
rating = int(input("Please rate your experience from 1 to 10: "))
if rating == 1:
    print("AI: I'm sorry to hear that your experience was not satisfactory. If there's anything specific you'd like to share or if you have any suggestions for improvement, please let me know. Your feedback is important to me.")
elif rating == 2:
    print("AI: I'm sorry to hear that your experience was not satisfactory. If there's anything specific you'd like to share or if you have any suggestions for improvement, please let me know. Your feedback is important to me.")
elif rating == 3:
    print("AI: I'm sorry to hear that your experience was not satisfactory. If there's anything specific you'd like to share or if you have any suggestions for improvement, please let me know. Your feedback is important to me.")
elif rating == 4:
    print("AI: I'm sorry to hear that your experience was not satisfactory. If there's anything specific you'd like to share or if you have any suggestions for improvement, please let me know. Your feedback is important to me.")
elif rating == 5:
    print("AI: Thank you for your feedback. I'm sorry to hear that your experience was not entirely satisfactory. If there's anything specific you'd like to share or if you have any suggestions for improvement, please let me know. Your input is valuable to me.")
elif rating == 7:
    print("AI: Thank you for your feedback. I'm glad to hear that your experience was somewhat satisfactory. If there's anything specific you'd like to share or if you have any suggestions for improvement, please let me know. Your input is valuable to me.")
elif rating == 8:
    print("AI: Thank you for your feedback. I'm glad to hear that your experience was somewhat satisfactory. If there's anything specific you'd like to share or if you have any suggestions for improvement, please let me know. Your input is valuable to me.")
elif rating == 9:
    print("AI: Thank you for your positive feedback! I'm glad to hear that your experience was satisfactory. If there's anything specific you'd like to share or if you have any suggestions for further improvement, please let me know. Your input is valuable to me.")
elif rating == 10:
    print("AI: Thank you for your positive feedback! I'm glad to hear that your experience was satisfactory. If there's anything specific you'd like to share or if you have any suggestions for further improvement, please let me know. Your input is valuable to me.")
