print(f'here are some Funny Passwords')
print('  ')
print('  ')
print(f'G!bR@lt@R2024')
print(f'5tr0nG#P@55w0rD')
print(f'S3cure&P@ss!')
print(f'    ')
print(f'    ')
print(f'here are some Weak Passwords')
print('  ')
print(f'123456')
print(f'password')
print(f'letmein')
print(f'    ')
print(f'    ')
print(f'Here are some Strong Passwords')
print('  ')
print(f'P@ssw0rd!2024')
print(f'S3cur3#Acc3ss')
print(f'MyP@ssw0rd$')
print(f'    ')
print(f'    ') 
print(f'Choose a password that is both strong and memorable!')
print(f'    ')
print(f'Good luck with your password!')
print(f'    ')
print(f'    ')
print(f'Password Tips:')
print(f'1. Use a mix of letters, numbers, and special characters.')
print(f'2. Avoid common words or phrases.')
print(f'3. Make it at least 12 characters long.')
print(f'4. Use a passphrase for added security.')
print(f'5. Change your passwords regularly.')
print(f'6. Use a password manager to keep track of your passwords.')
print(f'    ')
print(f'    ')

print(f'End of Password Suggestions')